### ISSUE TITLE
NodejsFunction lambdas don't match the command store

### ISSUE THREAD

**Issue by martzcodes** [cdklabs/cdk-app-cli#33]
NodejsFunctions end up with the fqn of `aws-cdk-lib.aws_lambda_nodejs.NodejsFunction` which don't match what's stored in the default `command-store.json` file, but they would inherently have the same commands.

I propose storing a list of aliases in the library and then the `command-store.ts` could normalize them before retrieving the commands.  Alternately... use the CloudFormation resource type instead, which would be consistent `"aws:cdk:cloudformation:type": "AWS::Lambda::Function",`

I'd be happy to contribute to the project.

**Comment by trobert2** [comment]
any chance of re-opening this issue?
